name: Deploy to Clojars

# Triggers the workflow on push of a tag
on:
  push:
    tags:
      - '*'

jobs:
  deploy_to_clojars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: '2.8.1'
      - uses: actions/checkout@v2

      - name: Lint Checks
        run: lein cljfmt check

      - name: Lein Kibit Check
        run: lein kibit

      - name: Run Tests on Kafka 1.x
        run: ./bin/run_tests_in_ci.sh
        env:
          KAFKA_VERSION: 1

      - name: Run Tests on Kafka 2.x
        run: ./bin/run_tests_in_ci.sh
        env:
          KAFKA_VERSION: 2

      - name: Calculate Coverage
        run: make coverage

      - name: Deploy to clojars
#        run: lein deploy clojars
        run: ls -l
        env:
            CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
            CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
