name: Ziggurat CI

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Lint Checks
      run: lein cljfmt check
    
    - name: Lein Kibit Check      
      run: lein kibit

